save-data:
  payments: "$.message.order.payments"
  cancellation_terms: "$.message.order.cancellation_terms"
  fulfillments: "$.message.order.fulfillments"
  on_init_tags: "$.message.order.tags"
  on_init_provider: "$.message.order.provider"
  on_init_items: "$.message.order.items"
  on_init_fulfillments: "$.message.order.fulfillments"