save-data:
  message_id: "$.context.message_id"
  selected_items: "$.message.order.items"
  select_fulfillments: "$.message.order.fulfillments"
  select_provider_id: "$.message.order.provider.id"
  select_provider: "$.message.order.provider"
