message:
  update_target: "order.quote"
  order:
    id: "BASE_ORDER_ID_1"
    fulfillments:
      - id: "F11"
        type: "AGENT_TICKETING"
        tags:
          - descriptor:
              code: "REF_ORDER_IDS"
            list:
              - descriptor:
                  code: "CHILD_ORDER_ID"
                  name: "Child Order Ids"
                value: "CHILD_ORDER_ID_1"
    quote:
      price:
        value: "2750"
        currency: "INR"
      breakup:
        - title: "BASE_FARE"
          item:
            id: "I1"
            quantity:
              selected:
                count: 50
          price:
            currency: "INR"
            value: "1750"
        - title: "BASE_FARE"
          item:
            id: "I2"
            price:
              currency: "INR"
              value: "25"
            quantity:
              selected:
                count: 40
          price:
            currency: "INR"
            value: "1000"
        - title: "OFFER"
          price:
            currency: "INR"
            value: "0"
        - title: "TOLL"
          price:
            currency: "INR"
            value: "0"
        - title: "TAX"
          price:
            currency: "INR"
            value: "0"
          item:
            tags:
              - descriptor:
                  code: "TAX"
                list:
                  - descriptor:
                      code: "CGST"
                    value: "0"
                  - descriptor:
                      code: "SGST"
                    value: "0"
        - title: "OTHER_CHARGES"
          price:
            currency: "INR"
            value: "0"
          item:
            tags:
              - descriptor:
                  code: "OTHER_CHARGES"
                list:
                  - descriptor:
                      code: "SURCHARGE"
                    value: "0"
