message:
  order:
    items:
      - id: "I10"
        descriptor:
          name: "Agent Login"
          code: "AGENT_TICKETING"
          images:
            - url: "https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png"
              size_type: "xs"
        category_ids:
          - "C1"
        price:
          currency: "INR"
          value: "0"
    provider:
      id: "P1"
      descriptor:
        name: "Delhi Transport Corporation"
        images:
          - url: "https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png"
            size_type: "xs"
    fulfillments:
      - id: "F1"
        type: "ROUTE"
        stops:
          - type: "START"
            location:
              descriptor:
                name: "kashmere gate"
                code: "KASHMERE_GATE"
              gps: "28.666576, 77.233332"
            id: "1"
          - type: "INTERMEDIATE_STOP"
            location:
              descriptor:
                name: "Indira Gandhi Technical Unviversity"
                code: "INDIRA_GANDHI_TECHNICAL_UNIV"
              gps: "28.624097, 77.204991"
            id: "2"
            parent_stop_id: "1"
          - type: "INTERMEDIATE_STOP"
            location:
              descriptor:
                name: "Yamuna Bazar"
                code: "YAMUNA_BAZAR"
              gps: "28.625972,77.209917"
            id: "3"
            parent_stop_id: "2"
          - type: "INTERMEDIATE_STOP"
            location:
              descriptor:
                name: "dhaula kuan"
                code: "DHAULA_KUAN"
              gps: "28.610972,77.201717"
            id: "4"
            parent_stop_id: "3"
          - type: "INTERMEDIATE_STOP"
            location:
              descriptor:
                name: "gpo"
                code: "GPO"
              gps: "28.623097,77.209917"
            id: "5"
            parent_stop_id: "4"
          - type: "END"
            location:
              descriptor:
                name: "Greater Kailash"
                code: "GREATER_KAILASH"
              gps: "28.548230, 77.238039"
            id: "6"
            parent_stop_id: "5"
        tags:
          - descriptor:
              code: "ROUTE_INFO"
            list:
              - descriptor:
                  code: "ROUTE_ID"
                value: "242"
              - descriptor:
                  code: "ROUTE_DIRECTION"
                value: "UP"
      - id: "F3"
        type: "ROUTE"
        stops:
          - type: "START"
            id: "1"
            location:
              descriptor:
                name: "kashmere gate"
                code: "KASHMERE_GATE"
              gps: "28.666576, 77.233332"
          - type: "INTERMEDIATE_STOP"
            id: "2"
            location:
              descriptor:
                name: "Indira Gandhi Technical Unviversity"
                code: "INDIRA_GANDHI_TECHNICAL_UNIV"
              gps: "28.624097, 77.204991"
            parent_stop_id: "1"
          - type: "END"
            id: "6"
            location:
              descriptor:
                name: "Greater Kailash"
                code: "GREATER_KAILASH"
              gps: "28.548230, 77.238039"
            parent_stop_id: "2"
        vehicle:
          category: "BUS"
        tags:
          - descriptor:
              code: "ROUTE_INFO"
            list:
              - descriptor:
                  code: "ROUTE_ID"
                value: "241"
              - descriptor:
                  code: "ROUTE_DIRECTION"
                value: "UP"
      - id: "F11"
        type: "AGENT_TICKETING"
        vehicle:
          category: "BUS"
          registration: "DL 11A 123F"
        agent:
          person:
            id: "emp:E52432"
        tags:
          - descriptor:
              code: "INFO"
            list:
              - descriptor:
                  code: "PARENT_ID"
                value: "F1"
      - id: "F12"
        type: "AGENT_TICKETING"
        vehicle:
          category: "BUS"
          registration: "DL 11A 124F"
        agent:
          person:
            id: "emp:E52432"
        tags:
          - descriptor:
              code: "INFO"
            list:
              - descriptor:
                  code: "PARENT_ID"
                value: "F2"
      - id: "F13"
        type: "AGENT_TICKETING"
        vehicle:
          category: "BUS"
          registration: "DL 11A 125F"
        agent:
          person:
            id: "emp:E52432"
        tags:
          - descriptor:
              code: "INFO"
            list:
              - descriptor:
                  code: "PARENT_ID"
                value: "F1"
      - id: "F14"
        type: "AGENT_TICKETING"
        vehicle:
          category: "BUS"
          registration: "DL 11A 126F"
        agent:
          person:
            id: "emp:E52432"
        tags:
          - descriptor:
              code: "INFO"
            list:
              - descriptor:
                  code: "PARENT_ID"
                value: "F2"
