save-data:
  confirm_message_id: "$.context.message_id"
  updated_payments: "$.message.order.payments[*]"
  buyer_side_fulfillment_ids: "$.message.order.fulfillments[*]"
  ttl: "$.context.ttl"
  confirm_tags: "$.message.order.tags"