message:
  order:
    ref_order_ids:
      - "BASE_ORDER_ID_1"
    id: "CHILD_ORDER_ID_1"
    items:
      - id: "I1"
        quantity:
          selected:
            count: 2
        price:
          currency: "INR"
          value: "35"
    provider:
      id: "P1"
    fulfillments:
      - type: "TRIP"
        stops:
          - type: "START"
            location:
              descriptor:
                name: "kashmere gate"
                code: "KASHMERE_GATE"
              gps: "28.666576, 77.233332"
            id: "1"
          - type: "INTERMEDIATE_STOP"
            instructions:
              name: "Stop 1"
            location:
              descriptor:
                name: "Indira Gandhi Technical Unviversity"
                code: "INDIRA_GANDHI_TECHNICAL_UNIV"
              gps: "28.624097, 77.204991"
            id: "2"
            parent_stop_id: "1"
          - type: "INTERMEDIATE_STOP"
            instructions:
              name: "Stop 2"
            location:
              descriptor:
                name: "Yamuna Bazar"
                code: "YAMUNA_BAZAR"
              gps: "28.625972,77.209917"
            id: "3"
            parent_stop_id: "2"
          - type: "INTERMEDIATE_STOP"
            instructions:
              name: "Stop 3"
            location:
              descriptor:
                name: "dhaula kuan"
                code: "DHAULA_KUAN"
              gps: "28.610972,77.201717"
            id: "4"
            parent_stop_id: "3"
          - type: "INTERMEDIATE_STOP"
            instructions:
              name: "Stop 4"
            location:
              descriptor:
                name: "gpo"
                code: "GPO"
              gps: "28.623097,77.209917"
            id: "5"
            parent_stop_id: "4"
          - type: "END"
            location:
              descriptor:
                name: "Greater Kailash"
                code: "GREATER_KAILASH"
              gps: "28.548230, 77.238039"
            id: "6"
            parent_stop_id: "5"
      - type: "TICKET"
        tags:
          - descriptor:
              code: "TICKET_INFO"
            list:
              - descriptor:
                  code: "NUMBER"
                value: "7ed21b6f"
      - type: "TICKET"
        tags:
          - descriptor:
              code: "TICKET_INFO"
            list:
              - descriptor:
                  code: "NUMBER"
                value: "5xd31b8f"
    quote:
      price:
        value: "70"
        currency: "INR"
      breakup:
        - title: "BASE_FARE"
          item:
            id: "I1"
            price:
              currency: "INR"
              value: "35"
            quantity:
              selected:
                count: 2
          price:
            currency: "INR"
            value: "70"
        - title: "OFFER"
          price:
            currency: "INR"
            value: "0"
        - title: "TOLL"
          price:
            currency: "INR"
            value: "0"
        - title: "TAX"
          price:
            currency: "INR"
            value: "0"
          item:
            tags:
              - descriptor:
                  code: "TAX"
                list:
                  - descriptor:
                      code: "CGST"
                    value: "0"
                  - descriptor:
                      code: "SGST"
                    value: "0"
        - title: "OTHER_CHARGES"
          price:
            currency: "INR"
            value: "0"
          item:
            tags:
              - descriptor:
                  code: "OTHER_CHARGES"
                list:
                  - descriptor:
                      code: "SURCHARGE"
                    value: "0"
    payments:
      - id: "PA1"
        collected_by: "BAP"
        status: "PAID"
        type: "PRE-ORDER"
        params:
          currency: "INR"
          amount: "70"
