message:
  order:
    id: O1
    status: ACTIVE
    items:
      - id: I8
        descriptor:
          name: Weekly Pass
          code: PASS
          images:
            - url: https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png
              size_type: xs
        fulfillment_ids:
          - F9
        price:
          currency: INR
          value: "100"
        quantity:
          selected:
            count: 1
        time:
          label: Validity
          duration: P7D
          timestamp: 2021-03-23T10:00:40.065Z
          range:
            start: 2021-03-23T10:00:40.065Z
            end: 2021-03-29T17:00:40.065Z
    provider:
      id: P1
      descriptor:
        name: Delhi Transport Corporation
        images:
          - url: https://dtc.delhi.gov.in/sites/default/files/DTC/logo/dtc_logo_2.png
            size_type: xs
    fulfillments:
      - id: F9
        type: PASS
        customer:
          person:
            creds:
              - type: PAN
                id: YKPYS1412V
        stops:
          - type: START
            location:
              descriptor:
                code: std:011
              gps: 28.666576, 77.233332
            authorization:
              type: QR
              token: aMOPw0KGgoAAAANSUhEUgAAAH0AAAB9AQAAAACn+1GINAAApklEQVR4Xu2UMQ4EMQgD/QP+/0vK6zjsvayUMmavWxQpMAUBkwS12wcveAAkgNSCD3rR5Lkgoai3GUCMgWqbAEYR3HxAkZlzU/0MyBisYRsgI1ERFfcpBpA+ze6k56Cj7KTdXNigFWZvSOpsgqLfd18i2aAukXh9TXBNmdWt5gzA/oqzWkkN8HtA7G8CNOwYAiZt3wZixUfkA32OHNQq7Bxs9oI/gC/9fV8AVCkPjQAAAABJRU5ErkJggg==
              valid_to: 2024-07-23T23:59:59.999Z
              status: UNCLAIMED
            id: "1"
        vehicle:
          category: BUS
          variant: AC
        tags:
          - descriptor:
              code: TICKET_INFO
            list:
              - descriptor:
                  code: NUMBER
                value: 7ed21b6f
    cancellation_terms:
      - cancel_by:
          duration: PT60M
        cancellation_fee:
          percentage: "0"
    billing:
      name: John Doe
      email: john.doe@example.com
      phone: +91-9897867564
    quote:
      price:
        value: "100"
        currency: INR
      breakup:
        - title: BASE_FARE
          item:
            id: I1
            price:
              currency: INR
              value: "100"
            quantity:
              selected:
                count: 1
          price:
            currency: INR
            value: "100"
        - title: OFFER
          price:
            currency: INR
            value: "0"
        - title: TOLL
          price:
            currency: INR
            value: "0"
        - title: TAX
          price:
            currency: INR
            value: "0"
          item:
            tags:
              - descriptor:
                  code: TAX
                list:
                  - descriptor:
                      code: CGST
                    value: "0"
                  - descriptor:
                      code: SGST
                    value: "0"
        - title: OTHER_CHARGES
          price:
            currency: INR
            value: "0"
          item:
            tags:
              - descriptor:
                  code: OTHER_CHARGES
                list:
                  - descriptor:
                      code: SURCHARGE
                    value: "0"
    payments:
      - id: PA1
        collected_by: BAP
        status: PAID
        type: PRE-ORDER
        params:
          transaction_id: 34cc9b0b-6887-4c63-8397-2f4fcf03e50d
          currency: INR
          amount: "100"
    tags:
      - descriptor:
          code: BAP_TERMS
          name: BAP Terms of Engagemen
        display: false
        list:
          - descriptor:
              code: BUYER_FINDER_FEES_PERCENTAGE
            value: "1"
          - descriptor:
              code: SETTLEMENT_WINDOW
            value: PT60M
          - descriptor:
              code: SETTLEMENT_BASIS
            value: Delivery
          - descriptor:
              code: SETTLEMENT_TYPE
            value: upi
          - descriptor:
              code: MANDATORY_ARBITRATION
            value: "true"
          - descriptor:
              code: COURT_JURISDICTION
            value: New Delhi
          - descriptor:
              code: DELAY_INTEREST
            value: "2.5"
          - descriptor:
              code: STATIC_TERMS
            value: https://www.abc.com/settlement-terms/
          - descriptor:
              code: SETTLEMENT_AMOUNT
            value: "12505"
      - descriptor:
          code: BPP_TERMS
          name: BPP Terms of Engagement
        display: false
        list:
          - descriptor:
              code: BUYER_FINDER_FEES_PERCENTAGE
            value: "1"
          - descriptor:
              code: SETTLEMENT_WINDOW
            value: PT60M
          - descriptor:
              code: SETTLEMENT_BASIS
            value: Delivery
          - descriptor:
              code: SETTLEMENT_TYPE
            value: upi
          - descriptor:
              code: MANDATORY_ARBITRATION
            value: "true"
          - descriptor:
              code: COURT_JURISDICTION
            value: New Delhi
          - descriptor:
              code: DELAY_INTEREST
            value: "2.5"
          - descriptor:
              code: STATIC_TERMS
            value: https://www.abc.com/settlement-terms/
          - descriptor:
              code: SETTLEMENT_AMOUNT
            value: "12505"
          - descriptor:
              code: SETTLEMENT_BANK_CODE
            value: XXXXXXXX
          - descriptor:
              code: SETTLEMENT_BANK_ACCOUNT_NUMBER
            value: xxxxxxxxxxxxxx
      - descriptor:
          code: ADDITIONAL_APIS
        display: false
        list:
          - descriptor:
              code: GTFS_RT
            value: https://api.transit-solutions/gtfs-realtime
    created_at: 2021-03-23T10:00:40.065Z
    updated_at: 2021-03-23T10:00:40.065Z
