save-data:
  on_select_items: "$.message.order.items"
  on_select_fulfillments: "$.message.order.fulfillments"
  on_select_quote: "$.message.order.quote"
  on_select_provider: "$.message.order.provider"
  on_select_tags: "$.message.order.tags"
