save-data:
  select_message_id: "$.context.message_id"
  agent_activation_item_id: "$.message.order.items[0].id"
  fulfillment_agent: "$.message.order.fulfillments[*].agent"
  agent_provider_id: "$.message.order.provider.id"